image:
  file: .gitpod/Dockerfile
  context: .gitpod
tasks:
  - init: >
      COREPACK_ENABLE_DOWNLOAD_PROMPT=0 make STRICT=false
    command: make serve

ports:
  - port: 8000
    onOpen: open-browser
    visibility: private
