tasks:
  - init: >
      nvm install 16 &&
      nvm use 16 &&
      pyenv install &&
      pip3 install pipenv &&
      make
    command: make serve

ports:
  - port: 8000
    onOpen: open-browser
    visibility: private
