name: Refactor (internal)
description: For internal use only.
labels: ['']
body:
  - type: markdown
    attributes:
      value: '# This form is for Renovate maintainers only.'

  - type: textarea
    id: describe-proposed-changes
    attributes:
      label: Describe the proposed change(s).
      description: 'Do not report any security concerns here. Email renovate-disclosure@mend.io instead.'
    validations:
      required: true
