name: lint

on:
  pull_request:
    branches:
      - 'build'
  push:
    branches:
      - 'build'
      - 'renovate/**'

env:
  node-version: 14.x

jobs:
  build:
    name: prettier
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@ec3a7ce113134d7a93b817d10a8272cb61118579 # renovate: tag=v2.4.0

      - name: Set up Node.js ${{ env.node-version }}
        uses: actions/setup-node@270253e841af726300e85d718a5f606959b2903c # renovate: tag=v2.4.1
        with:
          node-version: ${{ env.node-version }}
          cache: 'yarn'

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Run Prettier
        run: yarn prettier
